package com.example.Dev_Toolbox.controllers;

import com.example.Dev_Toolbox.entity.LinkHistory;
import com.example.Dev_Toolbox.entity.LinkStatus;
import com.example.Dev_Toolbox.repository.LinkHistoryRepository;
import com.example.Dev_Toolbox.util.SessionIds;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Link history is scoped to an anonymous session id (random UUID generated by the browser
 * and sent as X-Session-Id). No login / Spring Security involved.
 */
@RestController
@RequestMapping("/api/links")
@RequiredArgsConstructor
public class LinkHistoryController {

    private final LinkHistoryRepository linkHistoryRepository;

    @GetMapping("/history")
    public List<LinkHistory> getHistory(
            @RequestHeader(value = SessionIds.HEADER, required = false) String sessionHeader) {

        String sessionId = SessionIds.require(sessionHeader);
        LocalDateTime now = LocalDateTime.now();

        List<LinkHistory> history =
                linkHistoryRepository.findTop100BySessionIdOrderByCreatedAtDesc(sessionId);

        List<LinkHistory> newlyExpired = history.stream()
                .filter(l -> l.getExpiresAt() != null
                        && l.getExpiresAt().isBefore(now)
                        && l.getStatus() != LinkStatus.EXPIRED)
                .peek(l -> l.setStatus(LinkStatus.EXPIRED))
                .toList();

        if (!newlyExpired.isEmpty()) {
            linkHistoryRepository.saveAll(newlyExpired);
        }
        return history;
    }

    @DeleteMapping("/history/{id}")
    public ResponseEntity<Void> removeOne(
            @PathVariable Long id,
            @RequestHeader(value = SessionIds.HEADER, required = false) String sessionHeader) {

        String sessionId = SessionIds.require(sessionHeader);
        return linkHistoryRepository.findByIdAndSessionId(id, sessionId)
                .map(link -> {
                    linkHistoryRepository.delete(link);
                    return ResponseEntity.noContent().<Void>build();
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/history")
    public ResponseEntity<Void> clear(
            @RequestHeader(value = SessionIds.HEADER, required = false) String sessionHeader) {

        linkHistoryRepository.deleteBySessionId(SessionIds.require(sessionHeader));
        return ResponseEntity.noContent().build();
    }
}
